x = int(input("Enter your first number    : "))
y = int(input("Enter your second number   : "))
print("")
print("----------------------")
print(x,"+",y,"=",x+y)
print(x,"-",y,"=",x-y)
print(x,"*",y,"=",x*y)
print(x,"/",y,"=",int(x/y))
print("----------------------")